Fix the dowstream builds (#18)

diff --git a/downstream-build/action.yml b/downstream-build/action.yml
--- a/downstream-build/action.yml
+++ b/downstream-build/action.yml
@@ -13,7 +13,6 @@ runs:
         echo $PWD
         ls -lah
         cat <<'EOF' > ${GITHUB_WORKSPACE}/script_container.sh
-        /mount.sh
         cd ./Package
 
         source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh
@@ -24,7 +23,10 @@ runs:
         git clone https://github.com/spack/spack --single-branch -q
         cd spack
         git checkout $(cat $rel/.spack-commit)
-        source $rel/.cherry-pick
+        # This is not needed since very rarely a new dependency is in the cherry picks
+        # In addition the right commit for key4hep-spack should be used if this is
+        # to be sourced
+        # source $rel/.cherry-pick
         cd ..
 
         source spack/share/spack/setup-env.sh
@@ -39,12 +41,6 @@ runs:
         echo $name
 
         git clone https://github.com/key4hep/key4hep-dev-utils --depth 1 -q
-        latest_rel=$(find /cvmfs/sw-nightlies.hsf.org/key4hep/releases/ -maxdepth 3 -type f -wholename "*almalinux9*/.spack-commit" | sort -r | head -1)
-        latest_rel=$(dirname $latest_rel)
-        if [ "$rel" != "$latest_rel" ]; then \
-          spack config add "upstreams:nightly_latest:install_tree: $latest_rel"
-        fi
-        spack config add "upstreams:nightly:install_tree: $rel"
         mkdir /Workarea
         cd /Workarea
         python3 /Package/key4hep-dev-utils/scripts/fetch_and_checkout.py $name
@@ -70,11 +66,16 @@ runs:
             # echo $v is ${!v}
         done
 
+        status=0
         cd /Package/main
         mkdir build
         cd build
         cmake .. -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_CXX_STANDARD=20 -DBUILD_TESTING=OFF -G Ninja
         ninja && ninja install > /dev/null
+        build_ret=$?
+        if [ $build_ret -ne 0 ]; then
+            status=1
+        fi
         # Do not run the tests, this is already done in other CI workflows
         # ctest -j $(nproc) --output-on-failure
         cd ../install
@@ -92,7 +93,17 @@ runs:
             cd build
             cmake .. -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_CXX_STANDARD=20 -G Ninja
             ninja && ninja install > /dev/null
-            ctest -j $(nproc) --output-on-failure
+            build_ret=$?
+            if [ $build_ret -eq 0 ]; then
+                ctest -j $(nproc) --output-on-failure
+                test_ret=$?
+            else
+                test_ret=1
+                echo "Build failed for $package, skipping tests"
+            fi
+            if [ $build_ret -ne 0 ] || [ $test_ret -ne 0 ]; then
+                status=1
+            fi
             cd ../install
             export PATH=$PWD/bin:$PATH
             export LD_LIBRARY_PATH=$PWD/lib:$PWD/lib64:$LD_LIBRARY_PATH
@@ -101,6 +112,7 @@ runs:
             export CMAKE_PREFIX_PATH=$PWD:$CMAKE_PREFIX_PATH
             cd ../..
         done
+        exit $status
 
         EOF
 
