Build the main package and exit if there is an error

diff --git a/downstream-build/action.yml b/downstream-build/action.yml
--- a/downstream-build/action.yml
+++ b/downstream-build/action.yml
@@ -53,6 +53,23 @@ runs:
         cd /Workarea
         python3 /Package/key4hep-dev-utils/scripts/fetch_and_checkout.py $name "$branch_packages"
 
+        # Exit now if there is any command that fails
+        set -e
+
+        cd /Package/main
+        mkdir build
+        cd build
+        cmake .. -DCMAKE_INSTALL_PREFIX=../install -G Ninja
+        ninja install
+        ctest -j $(nproc)
+        cd ../install
+        export PATH=$PWD/bin:$PATH
+        export LD_LIBRARY_PATH=$PWD/lib:$PWD/lib64:$LD_LIBRARY_PATH
+        export ROOT_INCLUDE_PATH=$PWD/include:$ROOT_INCLUDE_PATH
+        export PYTHONPATH=$PWD/python:$PYTHONPATH
+        export CMAKE_PREFIX_PATH=$PWD:$CMAKE_PREFIX_PATH
+        cd /
+
         for package in $(ls)
         do
             cd $package
